format = """
$directory\
$git_branch\
$rust\
$nodejs\
$lua\
$line_break\
$character"""

[directory]
read_only = " ï ½"
format = ' [$path]($style)[$read_only]($read_only_style) '

[docker_context]
symbol = "ïŒˆ "

[git_branch]
symbol = "ï˜ "

[nodejs]
symbol = "îœ˜"
format = 'via [$symbol($version )]($style)'

[deno]
symbol = "ğŸ¦• "
format = 'via [$symbol($version )]($style)'

[rust]
symbol = "î¨"
format = 'via [$symbol($version )]($style)'

[lua]
symbol = "ğŸŒ™ "
format = 'via [$symbol($version )]($style)'

[character]
success_symbol = '[ î‰¢](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = "[ î‰¢](bold red)"
