format = """
$username\
$hostname\
$directory\
$git_branch\
$rust\
$nodejs\
$lua\
$line_break\
$character
"""

[username]
style_user = "green bold"
style_root = "red bold"
format = " [$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = "ğŸŒ "
format = 'on [$hostname](bold purple) '
trim_at = "."
disabled = false

[directory]
read_only = " ó°Œ¾"
format = '[$path]($style)[$read_only]($read_only_style) '

[docker_context]
symbol = "ïŒˆ "

[git_branch]
symbol = "ï˜ "

[nodejs]
symbol = "îœ˜ "
format = 'via [$symbol($version )]($style)'

[deno]
symbol = "ğŸ¦• "
format = 'via [$symbol($version )]($style)'

[rust]
symbol = "î¨ "
format = 'via [$symbol($version )]($style)'

[lua]
symbol = "ğŸŒ™ "
format = 'via [$symbol($version )]($style)'

[character]
success_symbol = '[ î‰¢](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = "[ î‰¢](bold red)"
