[default_session]
startup_command_ignore_dirs = ["~/repos", "~/.config"]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "second brain üß†"
path = "~/Documents/obsidian"
startup_command = "nvim"
preview_command = ""

[[session]]
name = "zapnote ‚ö°"
path = "~/repos/zapnote/"
startup_command = "~/.config/sesh/scripts/rust_bacon_lazygit"
preview_command = "bat --language=markdown --style=snip --color=always ~/repos/zapnote/README.md"

[[session]]
name = "nixos-config ‚ùÑÔ∏è"
path = "~/repos/nixos-config/"
startup_command = "~/.config/sesh/scripts/nixos-setup"

[[session]]
name = "dotfiles"
path = "~/repos/dotfiles/"
preview_command = ""
