[[session]]
name = "second brain ğŸ§ "
path = "~/Documents/obsidian"
startup_command = "nvim"

[[session]]
name = "dotfiles âœ¨"
path = "~/repos/dotfiles/"
startup_command = "nvim '+Telescope git_files'"

[[session]]
name = "zapnote âš¡"
path = "~/repos/zapnote/"
startup_script = "~/.config/sesh/scripts/rust_bacon_lazygit"

[[session]]
name = "nixos-config â„ï¸"
path = "~/repos/nixos-config/"
startup_script = "~/.config/sesh/scripts/nixos-setup"

[[session]]
name = "Home ğŸ "
path = "~"
startup_command = "l"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazicd"
